---

- name: "ansible testing enviroment"
  hosts: webservers
  remote_user: root
  become: yes
  tasks:
    - name: stop existing Backend container
      command: docker stop Test_Backend
      ignore_errors: yes

    - name: stop exisiting WITC container
      command: docker stop Test_WITC
      ignore_errors: yes

    - name: remove existing Backend container
      command: docker rm Test_Backend
      ignore_errors: yes

    - name: remove existing WITC container 
      command: docker rm Test_WITC
      ignore_errors: yes

    - name: remove existing WITC image
      command: docker image rm -f benstudent/witc:latest
    
    - name: remove existing Backend image
      command: docker image rm -f benstudent/witc_backend:latest

    - name: pull latest WITC image from dockerhub
      command: docker pull benstudent/witc:latest

    - name: pull latest Backend image from dockerhub
      command: docker pull benstudent/witc_backend:latest

    - name: run docker image WITC on port 81:81
      command: docker run --name Test_WITC --restart=always -d -p 81:81 benstudent/witc:latest
    
    - name: run docker image Backend on port 3100:3100
      command: docker run --name Test_Backend --restart=always -d -p 3100:3100 benstudent/witc_backend:latest




