---

- name: "Automation depmloyment playbook"
  hosts: local
  connection: local
  remote_user: root
  become: yes
  tasks:
    - name: install docker
      command: apt install docker
      ignore_errors: yes

    - name: build jenkins-docker image from dockerfile in same repo (only works if dockerfile is in repo)
      command: sudo docker build -t jenkins-docker . 
      

    - name: run jenkins container on port 9000
      command: sudo docker run -d --name jenkins -p 9000:8080 -v /var/run/docker.sock:/var/run/docker.sock jenkins-docker
      ignore_errors: yes

#    - name: exec in jenkins container
#      command: sudo docker exec -it jenkins bash
      

#    - name: install docker in jenkins container
#      command: sudo apt install docker.io

#    - name: install ssh in jenkins container
#      command: sudo apt install ssh
    
#    - name: install ansible in jenkins container
#      command: sudo apt install ansible

#    - name: exit exec jenkins
#      command: sudo exit

    - name: change vm.max_map_count temporarily
      command: sudo sysctl -w vm.max_map_count=262144

    - name: change vm.max_map_count for good
      command: sudo echo "vm.max_map_count=262144" >> /etc/sysctl.conf

    - name: run elk stack continer
      command: sudo docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 \ -v elk-data:/var/lib/elasticsearch --name elk sebp/elk
      ignore_errors: yes
    
    - name: run check-mk container
      command: sudo docker container run -dit -p 8080:5000 --ulimit nofile=1024 --tmpfs /opt/omd/sites/cmk/tmp:uid=1000,gid=1000 -v monitoring:/omd/sites --name monitoring -v /etc/localtime:/etc/localtime:ro --restart always checkmk/check-mk-raw:1.6.0-latest

    - name: show checkmk password
      command: sudo docker container logs monitoring

    - name: show jenkins password
      command: sudo docker container logs jenkins 
    



